### ISSUE TITLE
I have some question! 

### ISSUE THREAD

**Issue by kinmio** [ziyangyeh/Auto-Orth#9]
大佬您好，我这阵子都有在关注这TANet，感谢您提供了代码
但我在安装与运行过程中遇到一些error，明明已经有安装Pytorch 1.12.0但却一直显示
```
(tanet) kinmio@kinmio:~/TANet-Pytorch/scripts$ python test.py
Traceback (most recent call last):
File "/home/kinmio/TANet-Pytorch/scripts/test.py", line 7, in <module>
from models import LitModule
ModuleNotFoundError: No module named 'models'
```

或是我在运行TANet.py的时后也会显示
```
Traceback (most recent call last):
  File "/home/kinmio/TANet-Pytorch/models/TANet.py", line 4, in <module>
    from utils import get_learned_matrix
ImportError: cannot import name 'get_learned_matrix' from 'utils' (/home/kinmio/anaconda3/envs/tanet/lib/python3.9/site-packages/utils/__init__.py)
```

想请教这问题该如何解决?
不知道大佬有没有微信，可以多交流?
我的微信账号: Boe_0321

Hello, I've been following TANet recently and I appreciate you providing the code. However, I encountered some errors during installation and running. Even though I have installed PyTorch 1.12.0, it keeps showing an error.
```
(tanet) kinmio@kinmio:~/TANet-Pytorch/scripts$ python test.py
Traceback (most recent call last):
File "/home/kinmio/TANet-Pytorch/scripts/test.py", line 7, in <module>
from models import LitModule
ModuleNotFoundError: No module named 'models'
```
Or when I run TANet.py, it also shows an error.
```
Traceback (most recent call last):
  File "/home/kinmio/TANet-Pytorch/models/TANet.py", line 4, in <module>
    from utils import get_learned_matrix
ImportError: cannot import name 'get_learned_matrix' from 'utils' (/home/kinmio/anaconda3/envs/tanet/lib/python3.9/site-packages/utils/__init__.py)
```

I would like to ask how to solve this problem. I have tried many methods but still couldn't get it to run.
Thank you, Author.

**Comment by ziyangyeh** [comment]
This project is no longer maintained.
Here is another useful repo: 
https://github.com/huang229/auto_tooth_arrangement
